### ISSUE TITLE
test

### ISSUE THREAD

**Issue by devhyun637** [toggle-toggle/javascript-basic#1]
### 호출 스택이란?
실행할 코드에 제공할 환경 정보들을 모아놓은 객체이다. 자동으로 생성되는 전역공간을 제외하면 거의 함수 실행으로 이루어져 있다.
함수들이 호출되는 순서를 기억했다가 함수가 끝나면 원래 있던 자리로 돌아가기 위해 쓰이는 자료구조 중 하나이다. 모든 프로세스와 스레드에는 저마다의 call stack이 존재한다.
자바스크립트 내에서 함수가 호출되면, Call Stack에 push 실행이 되면 pop 해준다.
자바스크립트는 어떤 call stack이 활성화되는 시점에 선언된 변수를 위로 끌어올리고, 외부 환경 정보를 구성하고, this 값을 설정하는 등의 동작을 수행한다.

### 실행 context 
- this binding이란 무엇인지 더 공부해오기.

**Comment by Tanney-102** [comment]
comment test

**Comment by bucketHaneul** [comment]
함수의 this는 언제 바인딩? 초기화?가 될까??

**Comment by devhyun637** [comment]
호출 스택에 어떤 개념은 수정 필요하지 않을까?
어떤 개념 추가하면 좋을것같아

**Comment by jum0** [comment]
https://github.com/toggle-toggle/javascript-basic/issues/1#issuecomment-788817755
+ this가 초기화 되면 어떤 type일까?
