### ISSUE TITLE
[DOM & BOM] 렌더링(엔진)이란 무엇이고, 브라우저 렌더링은 어떻게 동작하는가?

### ISSUE THREAD

**Issue by bucketHaneul** [toggle-toggle/javascript-basic#17]
푸항항

**Comment by shinsehantan** [comment]
렌더링이란, 요청한 콘텐츠를 화면에 표시하는 것입니다. 예를 들어, HTML을 요청하면 HTML과 CSS를 파싱하여 화면에 표시합니다. 각 브라우저는 이 렌더링을 수행하는 렌더링 엔진을 가지는데 사파리는 webkit 엔진을, 파이어폭스는 gecko 엔진을, 크롬은 블링크 엔진을 사용합니다.
브라우저 렌더링 동작 과정에 대해 말씀드리면, 브라우저는 읽어들인 문서를 파싱하여 웹 페이지에 어떤 내용을 최종적으로 렌더링할 지 결정합니다. 브라우저는 그 결정된 내용으로 렌더링을 수행하는데 그 과정에서 HTML 요소들의 구조화된 표현인 DOM과 그 요소들과 연관된 스타일 정보의 구조화된 표현인 CSSOM 모델 2가지로 '렌더트리'를 생성합니다. 브라우저 뷰포트에는 이 DOM과 CSSOM의 조합인 '렌더 트리'가 보여지는 것입니다.
위와 같은 일련의 과정들은 동기적으로 진행되지는 않습니다. 브라우저는 HTML을 파싱할 때까지 기다리지 않고 렌더 트리 배치와 그리기 과정을 시작하는데 자세한 동작 과정은 각 렌더링 엔진에 따라 약간씩 다르다고 합니다.

**Comment by bucketHaneul** [comment]
HTML, CSS, JS 등 개발자가 작성한 코드 파일을 브라우저에 출력하는 과정을 `렌더링`이라하고, 이러한 역할을 하는 엔진을 `렌더링 엔진`이라 합니다.

렌더링 엔진의 동작 과정은 다음과 같습니다. 

가장 먼저, 요청에 대한 응답으로 받은 HTML문서를 파싱하여 DOM 객체를 생성해 나갑니다. 그렇게 HTML  문서를 파싱하다가, link 태그를 만나면 CSS파일과 style 요소를 파싱하여 CSSOM을 생성하는데요. 렌더링 엔진은 이렇게 생성된 DOM 객체와 CSSOM 객체를 합쳐서 render tree를 생성합니다.  그리고나서 render tree를 통해 각 노드를 화면에 표시하도록 배치합니다. 배치가 완성되면, UI  백엔드에서 render tree의 각 노드를 가로지르며 화면에 그리게 되고, 우리는 그렇게 브라우저에서 우리가 원하는 화면을 볼 수 있게됩니다. 추가로 <script> 태그를 만나면 렌더링 엔진은 자바스크립트 엔진을 실행하면서 자바스크립트 코드를 파싱하여 동적인 화면을 유저에게 보여줍니다.

**Comment by Tanney-102** [comment]
렌더링은 응답받은 문서를 브라우저에 보여주는 작업을 의미한다.

렌더링 과정은 다음과 같다.

1. 브라우저에 웹페이지를 요청하고 성공적으로 응답을 받으면 필요한 문서와 리소스들이 다운로드된다. 
2. 문서가 다운로드 되면 브라우저는 html파일을 파싱한다. 이때, link와 script태그를 만나면 각각 css와 js파일을 로드한다. 
3. html과 css 파일을 파싱하면서 DOM과 CSSOM이 구성된다. 
4. DOM과 CSSOM을 병합하여 렌더트리를 구성한다. 이때, 실제 화면에 영역을 차지하게 될 요소들만 포함한다.
5. 요소들이 배치될 위치와 실제 크기가 계산된다. 이 과정을 레이아웃 혹은 플로우(리플로우) 과정이라고 한다.
6. 각 요소를 픽셀 단위로 맵핑한다. 이때, 각 레이어 별로 처리되며 이 과정을 페인트(리페인트) 과정이라고 한다.
7. 픽셀단위로 준비된 각 레이어를 병합해 실제 뷰포트에 보여준다. 이 과정을 컴포지팅이라고한다.

참고 : [https://developers.google.com/web/updates/2018/09/inside-browser-part3?hl=ko](https://developers.google.com/web/updates/2018/09/inside-browser-part3?hl=ko)

**Comment by devhyun637** [comment]
큰 의미의 렌더링은 Html, CSS, JavaScript 등의 문서를 브라우저에서 볼 수 있는 형태로 출력하는 것을 의미합니다.
각각의 브라우저는 렌더링을 수행하기 위해 렌더링 엔진을 사용하는데, 각 브라우저 별로 엔진이 다르기 때문에 지원하는 범위나 성능이 조금씩 상이합니다. 대표적으로 파이어폭스는 게코를, 사파리는 웹킷을 사용합니다.

렌더링의 과정은 다음과 같습니다.
 1. 브라우저에게 웹페이지를 요청하고 응답하는 `request`, `response` 단계
 2. 성공적으로 요청과 응답이 이루어졌다면 `Html`을 `DOM` 요소로 변환하고, `CSS` 파일을 `CSSOM`으로 변환하는 `scripting` 단계
 3. `DOM`과 `CSSOM`에서 실제 화면에 그려질 부분에 대한 `Render Tree`를 형성하는 `rendering` 단계
 4. 각각의 요소들이 어떤 위치에 어떻게 배치될 것인지를 계산하는 `layout` 단계 (또는`reflow` 단계)
 5. 각 레이어별로 보여질 이미지를 비트맵 단위로 준비하는 `painting` 단계
 6. 준비한 레이어를 쌓아서 실제 사용자에게 보여주는 `composition` 단계

**Comment by jum0** [comment]
렌더링이란 브라우저에 나타나는 것을 말합니다. 브라우저가 렌더링하는 과정은 다음과 같습니다. 먼저 브라우저는 HTML, CSS, 자바스크립, 이미지, 폰트 파일 등 렌더링에 필요한 리소스를 요청하고 서버로부터 응답을 받습니다. 이후, 브라우저 렌더링 엔진은 서버로부터 응답된 HTML과 CSS를 파싱하여 DOM과 CSSOM(Javascript에서 CSS를 조작할 수 있는 API 집합)을 생성하고 이들을 결합하여 렌더 트리(이건 또 뭐냐)를 생성합니다. 브라우저의 자바스크립트 엔진은 서버로부터 응답된 자바스크립트를 파싱하여 AST(Abstract Syntax Tree)를 생성하고 바이트코드로 변환하여 실행합니다. 이때 자바스크립트는 DOM API를 통해 DOM이나 CSSOM을 변경할 수 있습니다. 변경된 DOM과 CSSOM은 다시 렌더 트리로 결합됩니다. 마지막으로 렌더 트리는 기반으로 HTML 요소의 레이아웃(위치와 크기)을 계산하고 브라우저 화면에 HTML 요소를 페인팅합니다.

**Comment by ddongule** [comment]
렌더링이란 response받은 문서를 브라우저에 보여주는 것을 의미합니다. 렌더링 과정은 아래와 같습니다.
[ DOM Tree 구축을 위한 HTML 파싱 → 렌더 트리 구축 → 렌더 트리 배치 → 렌더트리 그리기 ]
렌더링 엔진은 HTML 문서를 파싱하고 "콘텐츠 트리" 내부에서 태그를 DOM 노드로 변환합니다. 그 다음 외부 CSS 파일과 함께 포함된 스타일 요소도 파싱한다. 스타일 정보와 HTML 표시 규칙은 "렌더 트리"라고 부르는 또 다른 트리를 생성합니다. 렌더 트리는 색상 또는 면적과 같은 시각적 속성이 있는 사각형을 포함하고 있는데 정해진 순서대로 화면에 표시됩니다. 렌더 트리의 생성이 끝나면 배치가 시작되는데 이것은 각 노드가 화면의 정확한 위치에 표시되는 것을 의미합니다.
